# Generated by Django 4.0.4 on 2022-05-23 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('installations', '0002_status_installation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='installation',
            options={'ordering': ['-date_modified'], 'permissions': [('view_history', 'Can view history')]},
        ),
    ]
